const leaderData = [
    {
        'id':1,
        'srno':'01',
        'names':'names',
    },
    {
        'id':2,
        'srno':'02',
        'names':'names',
    },
    {
        'id':3,
        'srno':'03',
        'names':'You',
    },
    {
        'id':4,
        'srno':'04',
        'names':'names',
    },
    {
        'id':5,
        'srno':'05',
        'names':'names',
    },
    {
        'id':6,
        'srno':'06',
        'names':'names',
    },
    {
        'id':7,
        'srno':'07',
        'names':'names',
    },
    {
        'id':8,
        'srno':'08',
        'names':'names',
    },
    {
        'id':9,
        'srno':'09',
        'names':'names',
    },
    {
        'id':10,
        'srno':'01',
        'names':'names',
    },
    {
        'id':11,
        'srno':'10',
        'names':'names',
    },
    {
        'id':12,
        'srno':'11',
        'names':'names',
    },
    {
        'id':13,
        'srno':'12',
        'names':'names',
    },
]

export default leaderData;
